language: node_js
sudo: required

node_js:
  - '5'
  - '6'
  - '7'
  - '8'

cache:
  directories:
      - node_modules

env:
  - TRAVIS_HOST=127.0.0.1

services:
  - docker

before_install:
  - docker pull rqlite/rqlite
  - docker run -p 127.0.0.1:4001:4001 -p 127.0.0.1:4002:4002 rqlite/rqlite
  - docker ps -a

after_script:
  - npm run coveralls
